package com.order.enumaration;

public enum OrderHistoryType {
	
	ORDER_PLACED, ORDER_CONFIRMED, PAYMENT_COMPLETED, PAYMENT_FAILED, ORDER_SHIPPED, ORDER_DELIVERED, ORDER_CANCELLED, RETURN_REQUESTED, ORDER_RETURNED, REFUND_REQUEST, REFUND_COMPLETED 

}
